### ISSUE TITLE
Questions about the assignment

### ISSUE THREAD

**Issue by soccergurl123** [alecjacobson/geometry-processing-introduction#20]
What assumptions can we make about the mesh?

Related to computing E:
Will the mesh be a closed mesh (I'm not sure if this is equivalent to calling it a manifold without boundary) or will it be a similar to a manifold with boundary?  I assumed the former. Assuming the latter is just slightly more involved, I believe.

Related to computing |V|:
Is the vertex indexing 0-based or 1-based? I assumed 0-based. Technically, does not matter, knowing if it's 0 or 1 based allows for some easier hacks.

Does the assumption of no unreferenced vertices in V mean the following two statements?
The range of F is an onto mapping to the vertex indices.
The indexing of the vertices is consecutive.

**Comment by GavinBarill** [comment]
Hey Mian, 
Here's my best guess at some of your questions:

What assumptions can we make about the mesh?

Related to computing E:
I don't know, it'd be nice to know the answer since I could optimize my code. I'm assuming not, since the original definition of Euler characteristic involves a term for the boundary of the surface.

Related to computing |V|:
The indexing of the vertices starts at 0.

Does the assumption of no unreferenced vertices in V mean the following two statements?
The range of F is an onto mapping to the vertex indices (Yes)
The indexing of the vertices is consecutive. (This is answered by the previous point about the mapping being onto. If that doesn't make sense, then reread the definition of F)

**Comment by andrewoftoronto** [comment]
Hello,
I spoke to the professor and he told me that the assignment is basically intended to be easy (a way to get us to set up cmake, etc. properly) and that the main work is in the edges function. Moreover, he said that the computation involved was basically just summing the number of edges, vertices and faces, which of course, means you probably can assume it is a polyhedral surface and use that formula.
