### ISSUE TITLE
Manifold Mesh Only For A1?

### ISSUE THREAD

**Issue by TRDizer** [alecjacobson/geometry-processing-introduction#74]
For the scope of this assignment, should we consider the following cases:

- 2 triangles share an edge while the edge is still directed (eg. CW and CCW occurring on 2 adjacent faces)
- more than 2 triangles sharing 1 edge
- unreferenced vertex

**Comment by chanlenn** [comment]
- we are only considering UNdirected edges and not directed
- I don't see a reason why edges won't be able to do this
- dunno about this one

**Comment by ahurka** [comment]
I think in this assignment we can assume that all edges are used by exactly two triangles, and that there are no unreferenced vertices. Otherwise the formula we have for Euler characteristic would stop working and just be returning meaningless numbers.

Also see the last paragraph in Background. More reasons to expect no unreferenced vertices in inputs.
